# Generated by Django 5.2.1 on 2025-05-28 16:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discounts', '0001_initial'),
        ('items', '0003_item_created_at_item_updated_at'),
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discounts', models.ManyToManyField(related_name='discounts', to='discounts.discount')),
                ('items', models.ManyToManyField(related_name='items', to='items.item')),
                ('taxes', models.ManyToManyField(related_name='taxes', to='taxes.tax')),
            ],
        ),
    ]
