# Generated by Django 5.2.1 on 2025-05-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_discount_name'),
        ('orders', '0001_initial'),
        ('taxes', '0002_remove_tax_name_tax_type_alter_tax_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discounts',
            field=models.ManyToManyField(blank=True, related_name='discounts', to='discounts.discount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='taxes', to='taxes.tax'),
        ),
    ]
