# Generated by Django 5.2.1 on 2025-05-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='name',
        ),
        migrations.AddField(
            model_name='tax',
            name='type',
            field=models.TextField(choices=[('vat', 'Vat'), ('sales_tax', 'Sales Tax'), ('gst', 'Gst')], default='vat'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
