# Generated by Django 5.2.1 on 2025-05-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration', models.CharField(choices=[('once', 'Once'), ('forever', 'Forever'), ('repeating', 'Repeating')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid', models.BooleanField(default=True)),
            ],
        ),
    ]
