# Generated by Django 5.2.1 on 2025-05-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='duration',
            field=models.TextField(choices=[('once', 'Once'), ('forever', 'Forever'), ('repeating', 'Repeating')], default='once'),
        ),
    ]
