services:
  app:
    container_name: app
    build: ..
    # ports:
    #   - "8000:8000"
    volumes:
      - ../project:/app/project
    env_file:
      - ../.env
    depends_on:
      - postgres
    stdin_open: true
    tty: true

  postgres:
    container_name: postgres
    image: postgres:17
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  postgres_data:
