services:
  app:
    container_name: app
    image: oshinoko/stripe-test:latest
    env_file:
      - ../.env
    depends_on:
      - postgres
    stdin_open: true
    tty: true

  postgres:
    container_name: postgres
    image: postgres:17
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
