# Generated by Django 5.2.1 on 2025-05-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_created_at_item_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('USD', 'Usd'), ('RUB', 'Rub')], default='RUB'),
        ),
    ]
